# From https://github.com/rust-lang/mdBook/pull/1248
name: Book
on:
  push:
    branches:
      - main
jobs:
  book:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install mdbook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "latest"

      - name: Install mdbook-toc
        run: cargo install mdbook-toc

      - name: Generate book from markdown
        run: |
            cd book
            mdbook build

      # Build the npm landing page
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install node dependencies
        run: |
            cd landing_page
            npm ci

      - name: Build node
        run: |
            cd landing_page
            npm run build
            mv build ../book/book/landing_page

      - name: Publish HTML
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/book/
